name: Deploy Terraform orderly db Configuration

on: [push, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false
        terraform_version: 1.6.1  

    - name: Initialize Terraform
      run: |
        terraform init \
        -backend-config="bucket=${{ vars.BUCKET_NAME }}" \
        -backend-config="prefix=terraform-state/db"

    - name: Apply Terraform
      run: |
        terraform apply -auto-approve \
        -var="project_id=${{ vars.PROJECT_ID }}" \
        -var="region=${{ vars.REGION }}" \
        -var="zone=${{ vars.ZONE }}" \
        -var="db_username=${{ vars.DB_USERNAME }}" \
        -var="db_password=${{ secrets.DB_PASSWORD }}" \